## Name : Muhammad Anus
## Roll no : 24F-AI-077

# LAB 7: Open Ended - Student Performance Predictor

## 1. Data Preprocessing

In [19]:
import pandas as pd
df_por = pd.read_csv('student-por.csv', sep=';')
df_mat = pd.read_csv('student-mat.csv', sep=';')

In [20]:
df_por.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [21]:
df_mat.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [22]:
df_por.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [23]:
df_mat.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [24]:
df_mat.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [25]:
df_por.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [26]:
df_mat.shape

(395, 33)

In [27]:
df_por.shape

(649, 33)

In [28]:
cols = ['school','sex','age','address','famsize','Pstatus','Medu','Fedu','Mjob','Fjob','reason','guardian']

common = pd.merge(df_mat, df_por, on=cols, how='inner')

print(f"Common students: {len(common)}")

Common students: 383

In [29]:
# I am using student_por because it has more data than student_mat, I am not merging these to datasets because 383 rows are common in both datasets
data = df_por
data.shape

(649, 33)

In [30]:
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [31]:
df_encoded = pd.get_dummies(data, drop_first=True, dtype=int)

## PART 1: LINEAR REGRESSION

In [32]:
from sklearn.model_selection import train_test_split
X_reg = df_encoded.drop('G3', axis=1)
y_reg = df_encoded['G3']

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42

)

In [33]:
# Scaling features
from sklearn.preprocessing import StandardScaler
scaler_reg = StandardScaler()
X_train_r_scaled = scaler_reg.fit_transform(X_train_r)
X_test_r_scaled = scaler_reg.transform(X_test_r)

In [34]:
# Model Training
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train_r_scaled, y_train_r)

LinearRegression()

In [35]:
from sklearn.metrics import mean_squared_error
y_pred_r = lr.predict(X_test_r_scaled)

print("--- REGRESSION RESULT ---")
print("Linear Regression MSE:", mean_squared_error(y_test_r, y_pred_r))

--- REGRESSION RESULT ---
Linear Regression MSE: 1.4759092563639324

## PART 2: CLASSIFICATION

In [36]:
# Target Variable: 1 if G3 >= 10 (Pass), else 0 (Fail)
df_clf = df_encoded.copy()
y_clf = (df_clf['G3'] >= 10).astype(int)
X_clf = df_clf.drop('G3', axis=1)

In [37]:
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X_clf, y_clf, test_size=0.2, random_state=42, stratify=y_clf
)

In [38]:
# Scaling features
scaler_clf = StandardScaler()
X_train_c_scaled = scaler_clf.fit_transform(X_train_c)
X_test_c_scaled = scaler_clf.transform(X_test_c)

### 1. Logistic Regression

In [39]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_c_scaled, y_train_c)

LogisticRegression(max_iter=1000)

In [40]:
pred_log = log_reg.predict(X_test_c_scaled)

In [41]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
print("Logistic Regression Metrics:")
print("  Accuracy :", accuracy_score(y_test_c, pred_log))
print("  Precision:", precision_score(y_test_c, pred_log))
print("  Recall   :", recall_score(y_test_c, pred_log))
print("  Confusion Matrix:\n", confusion_matrix(y_test_c, pred_log))

Logistic Regression Metrics:
  Accuracy : 0.9076923076923077
  Precision: 0.9375
  Recall   : 0.9545454545454546
  Confusion Matrix:
 [[ 13   7]
 [  5 105]]

# 2. Decision Tree Classifier

In [42]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_c, y_train_c)

DecisionTreeClassifier(random_state=42)

In [45]:
pred_dt = dt.predict(X_test_c)

In [46]:
print("\nDecision Tree Metrics:")
print("  Accuracy :", accuracy_score(y_test_c, pred_dt))
print("  Precision:", precision_score(y_test_c, pred_dt))
print("  Recall   :", recall_score(y_test_c, pred_dt))
print("  Confusion Matrix:\n", confusion_matrix(y_test_c, pred_dt))

Decision Tree Metrics:
  Accuracy : 0.8538461538461538
  Precision: 0.9252336448598131
  Recall   : 0.9
  Confusion Matrix:
 [[12  8]
 [11 99]]