# LAB 7: Open Ended

## 1. Data Preprocessing

In [16]:
import pandas as pd
df_por = pd.read_csv('student-por.csv', sep=';')
df_mat = pd.read_csv('student-mat.csv', sep=';')

In [14]:
df_por.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [17]:
df_mat.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [25]:
df_por.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [24]:
df_mat.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [28]:
df_mat.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [29]:
df_por.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [26]:
df_mat.shape

(395, 33)

In [27]:
df_por.shape

(649, 33)

In [30]:
cols = ['school','sex','age','address','famsize','Pstatus','Medu','Fedu','Mjob','Fjob','reason','guardian']

common = pd.merge(df_mat, df_por, on=cols, how='inner')

print(f"Common students: {len(common)}")

Common students: 383

In [57]:
# I am using student_por because it has more data than student_mat, I am not merging these to datasets because 383 rows are common in both datasets
data = df_por
data.shape

(649, 33)

In [58]:
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [59]:
enc_column = data.select_dtypes(include='object').columns.tolist()

In [60]:
data = pd.get_dummies(data, enc_column, drop_first=True,dtype=int)

In [61]:
data.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,guardian_mother,guardian_other,schoolsup_yes,famsup_yes,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,1,0,1,0,0,0,1,1,0,0
1,17,1,1,1,2,0,5,3,3,1,...,0,0,0,1,0,0,0,1,1,0
2,15,1,1,1,2,0,4,3,2,2,...,1,0,1,0,0,0,1,1,1,0
3,15,4,2,1,3,0,3,2,2,1,...,1,0,0,1,0,1,1,1,1,1
4,16,3,3,1,2,0,4,3,2,1,...,0,0,0,1,0,0,1,1,0,0

In [62]:
scale_cols = data.select_dtypes(include=['int64','float64']).columns.tolist()

In [63]:
if 'G3' in scale_cols:
    scale_cols.remove('G3')

In [64]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [72]:
X = data.drop('G3', axis=1)
y = data['G3']

In [73]:
from sklearn.model_selection import train_test_split
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X, y, test_size=0.2, random_state=42)

In [76]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
lr = LinearRegression()
lr.fit(X_train_r, y_train_r)

LinearRegression()

In [77]:
y_pred_r = lr.predict(X_test_r)
print("Linear Regression MSE:", mean_squared_error(y_test_r, y_pred_r))

Linear Regression MSE: 0.0

In [83]:
# Needed binary labels for classification so I used lambda to convert grades to 0 and 1
data['G3'] = data['G3'].apply(lambda x: 1 if x >= 10 else 0)

In [84]:
X = data.drop('G3', axis=1)
y = data['G3']

In [90]:
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [93]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train_c, y_train_c)

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: np.int64(0)

In [94]:
# TIme end ho gya tha

In [87]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, mean_squared_error

# Data load
data = pd.read_csv('student-por.csv', sep=';')

# --- PART 1: LINEAR REGRESSION (Final marks prediction) ---
scale_cols = data.select_dtypes(include=['int64','float64']).columns.tolist()
scale_cols.remove('G3')

scaler = StandardScaler()
data[scale_cols] = scaler.fit_transform(data[scale_cols])

X_reg = data.drop('G3', axis=1)
y_reg = data['G3'] # 0-20 marks

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

lr = LinearRegression()
lr.fit(X_train_r, y_train_r)
y_pred_r = lr.predict(X_test_r)
print("Linear Regression MSE:", mean_squared_error(y_test_r, y_pred_r))

# --- PART 2: CLASSIFICATION (Pass/Fail) ---
# Create binary target
data_class = data.copy()
data_class['G3_binary'] = data_class['G3'].apply(lambda x: 1 if x >= 10 else 0) # 1=Pass, 0=Fail

X_clf = data_class.drop(['G3', 'G3_binary'], axis=1)
y_clf = data_class['G3_binary']

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_clf, y_clf, test_size=0.2, random_state=42)

# Logistic Regression
log_reg = LogisticRegression()
log_reg.fit(X_train_c, y_train_c)
pred_log = log_reg.predict(X_test_c)

# Decision Tree
dt = DecisionTreeClassifier()
dt.fit(X_train_c, y_train_c)
pred_dt = dt.predict(X_test_c)

# Compare
print("\nLogistic Regression:")
print("Accuracy:", accuracy_score(y_test_c, pred_log))
print("Precision:", precision_score(y_test_c, pred_log))
print("Recall:", recall_score(y_test_c, pred_log))

print("\nDecision Tree:")
print("Accuracy:", accuracy_score(y_test_c, pred_dt))
print("Precision:", precision_score(y_test_c, pred_dt))
print("Recall:", recall_score(y_test_c, pred_dt))

ValueError: could not convert string to float: 'GP'

0      1
1      1
2      1
3      1
4      1
      ..
644    1
645    1
646    0
647    1
648    1
Name: G3, Length: 649, dtype: int64